add_executable(dynamic_cast dynamic_cast.cpp)
add_executable(dynamic_type dynamic_type.cpp)
add_executable(empty_base empty_base.cpp)
add_executable(exception exception.cpp)
add_executable(inherit_access inherit_access.cpp)
add_executable(inherit_model inherit_model.cpp)
add_executable(inherit_type inherit_type.cpp)
add_executable(virtual_function virtual_function.cpp)
add_executable(virtual_inherit virtual_inherit.cpp)
