add_executable(array array.cpp)
add_executable(bitfield bitfield.cpp)
add_executable(copy-assigment copy-assigment.cpp)
add_executable(copy-ctor-init copy-ctor-init.cpp)
add_executable(memory-error memory-error.cpp)
add_executable(object_function object_function.cpp)
add_executable(object_layout object_layout.cpp)
add_executable(object_model object_model.cpp)
add_executable(point_reference point_reference.cpp)
add_executable(stack_heap stack_heap.cpp)
add_executable(string_demo string_demo.cpp)
add_executable(vector_array vector_array.cpp)
